<?xml version='1.0' encoding='UTF-8' standalone='yes'?>

<!DOCTYPE Workspace
[
    <!ELEMENT Workspace (Value*,Ravel*,SymbolTable,Symbol*,Commands,StateIndicator)>
    <!ATTLIST Workspace  wsid       CDATA #REQUIRED>
    <!ATTLIST Workspace  year       CDATA #REQUIRED>
    <!ATTLIST Workspace  month      CDATA #REQUIRED>
    <!ATTLIST Workspace  day        CDATA #REQUIRED>
    <!ATTLIST Workspace  hour       CDATA #REQUIRED>
    <!ATTLIST Workspace  minute     CDATA #REQUIRED>
    <!ATTLIST Workspace  second     CDATA #REQUIRED>
    <!ATTLIST Workspace  timezone   CDATA #REQUIRED>
    <!ATTLIST Workspace  saving_SVN CDATA #REQUIRED>

        <!ELEMENT Value (#PCDATA)>
        <!ATTLIST Value flg    CDATA #REQUIRED>
        <!ATTLIST Value vid    CDATA #REQUIRED>
        <!ATTLIST Value parent CDATA #IMPLIED>
        <!ATTLIST Value rk     CDATA #REQUIRED>
        <!ATTLIST Value sh-0   CDATA #IMPLIED>
        <!ATTLIST Value sh-1   CDATA #IMPLIED>
        <!ATTLIST Value sh-2   CDATA #IMPLIED>
        <!ATTLIST Value sh-3   CDATA #IMPLIED>
        <!ATTLIST Value sh-4   CDATA #IMPLIED>
        <!ATTLIST Value sh-5   CDATA #IMPLIED>
        <!ATTLIST Value sh-6   CDATA #IMPLIED>
        <!ATTLIST Value sh-7   CDATA #IMPLIED>

        <!ELEMENT Ravel (#PCDATA)>
        <!ATTLIST Ravel vid    CDATA #REQUIRED>
        <!ATTLIST Ravel cells  CDATA #REQUIRED>

        <!ELEMENT SymbolTable (Symbol*)>
        <!ATTLIST SymbolTable size CDATA #REQUIRED>

            <!ELEMENT Symbol (unused-name|Variable|Function|Label|Shared-Variable)*>
            <!ATTLIST Symbol name       CDATA #REQUIRED>
            <!ATTLIST Symbol stack-size CDATA #REQUIRED>

                <!ELEMENT unused-name EMPTY>

                <!ELEMENT Variable (#PCDATA)>
                <!ATTLIST Variable vid CDATA #REQUIRED>

                <!ELEMENT Function (UCS)>
                <!ATTLIST Function creation-time   CDATA #IMPLIED>
                <!ATTLIST Function exec-properties CDATA #IMPLIED>

                <!ELEMENT Label (#PCDATA)>
                <!ATTLIST Label value CDATA #REQUIRED>

                <!ELEMENT Shared-Variable (#PCDATA)>
                <!ATTLIST Shared-Variable key CDATA #REQUIRED>

        <!ELEMENT UCS (#PCDATA)>
        <!ATTLIST UCS uni CDATA #REQUIRED>

        <!ELEMENT Commands (Command*)>
        <!ATTLIST Commands size CDATA #REQUIRED>

            <!ELEMENT Command (#PCDATA)>
            <!ATTLIST Command name       CDATA #REQUIRED>
            <!ATTLIST Command mode       CDATA #REQUIRED>
            <!ATTLIST Command fun       CDATA #REQUIRED>

        <!ELEMENT StateIndicator (SI-entry*)>
        <!ATTLIST StateIndicator levels CDATA #REQUIRED>

            <!ELEMENT SI-entry ((Execute|Statements|UserFunction),Parser+)>
            <!ATTLIST SI-entry level     CDATA #REQUIRED>
            <!ATTLIST SI-entry pc        CDATA #REQUIRED>
            <!ATTLIST SI-entry line      CDATA #REQUIRED>

                <!ELEMENT Statements (UCS)>

                <!ELEMENT Execute (UCS)>

                <!ELEMENT UserFunction (#PCDATA)>
                <!ATTLIST UserFunction ufun-name       CDATA #IMPLIED>
                <!ATTLIST UserFunction macro-num       CDATA #IMPLIED>
                <!ATTLIST UserFunction lambda-name     CDATA #IMPLIED>
                <!ATTLIST UserFunction symbol-level    CDATA #IMPLIED>

                <!ELEMENT Parser (Token*)>
                <!ATTLIST Parser size           CDATA #REQUIRED>
                <!ATTLIST Parser assign-pending CDATA #REQUIRED>
                <!ATTLIST Parser lookahead-high CDATA #REQUIRED>
                <!ATTLIST Parser action         CDATA #REQUIRED>
                    <!ELEMENT Token (#PCDATA)>
                    <!ATTLIST Token pc           CDATA #REQUIRED>
                    <!ATTLIST Token tag          CDATA #REQUIRED>
                    <!ATTLIST Token char         CDATA #IMPLIED>
                    <!ATTLIST Token int          CDATA #IMPLIED>
                    <!ATTLIST Token float        CDATA #IMPLIED>
                    <!ATTLIST Token real         CDATA #IMPLIED>
                    <!ATTLIST Token imag         CDATA #IMPLIED>
                    <!ATTLIST Token sym          CDATA #IMPLIED>
                    <!ATTLIST Token line         CDATA #IMPLIED>
                    <!ATTLIST Token vid          CDATA #IMPLIED>
                    <!ATTLIST Token index        CDATA #IMPLIED>
                    <!ATTLIST Token fun-id       CDATA #IMPLIED>
                    <!ATTLIST Token ufun-name    CDATA #IMPLIED>
                    <!ATTLIST Token symbol-level CDATA #IMPLIED>
                    <!ATTLIST Token comment      CDATA #IMPLIED>

]>


    <!-- hour/minute/second is )SAVE time in UTC (aka. GMT).
         timezone is offset to UTC in seconds.
         local time is UTC + offset -->
<Workspace wsid="plotsincos" year="2020" month="6" day="30"
           hour="1" minute="26" second="20" timezone="-14400"
           saving_SVN=" 1258">

  <Value flg="0x400" vid="0" parent="-1" rk="1" sh-0="21"/>
  <Value flg="0x400" vid="1" parent="-1" rk="1" sh-0="5"/>
  <Value flg="0x400" vid="2" parent="-1" rk="1" sh-0="256"/>
  <Value flg="0x400" vid="3" parent="-1" rk="0"/>
  <Value flg="0x400" vid="4" parent="-1" rk="0"/>
  <Value flg="0x400" vid="5" parent="-1" rk="0"/>
  <Value flg="0x400" vid="6" parent="-1" rk="0"/>
  <Value flg="0x400" vid="7" parent="-1" rk="0"/>
  <Value flg="0x400" vid="8" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="9" parent="-1" rk="0"/>
  <Value flg="0x400" vid="10" parent="-1" rk="0"/>
  <Value flg="0x400" vid="11" parent="-1" rk="0"/>
  <Value flg="0x400" vid="12" parent="-1" rk="0"/>
  <Value flg="0x400" vid="13" parent="-1" rk="0"/>
  <Value flg="0x400" vid="14" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="15" parent="-1" rk="1" sh-0="3"/>
  <Value flg="0x400" vid="16" parent="-1" rk="0"/>
  <Value flg="0x400" vid="17" parent="-1" rk="0"/>
  <Value flg="0x400" vid="18" parent="-1" rk="0"/>
  <Value flg="0x400" vid="19" parent="-1" rk="1" sh-0="6"/>
  <Value flg="0x400" vid="20" parent="-1" rk="0"/>
  <Value flg="0x400" vid="21" parent="-1" rk="1" sh-0="1"/>
  <Value flg="0x400" vid="22" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="23" parent="-1" rk="0"/>
  <Value flg="0x400" vid="24" parent="-1" rk="0"/>
  <Value flg="0x400" vid="25" parent="-1" rk="0"/>
  <Value flg="0x400" vid="26" parent="-1" rk="0"/>
  <Value flg="0x400" vid="27" parent="-1" rk="0"/>
  <Value flg="0x400" vid="28" parent="-1" rk="0"/>
  <Value flg="0x400" vid="29" parent="-1" rk="0"/>
  <Value flg="0x400" vid="30" parent="-1" rk="0"/>
  <Value flg="0x400" vid="31" parent="-1" rk="0"/>
  <Value flg="0x400" vid="32" parent="-1" rk="0"/>
  <Value flg="0x400" vid="33" parent="-1" rk="0"/>
  <Value flg="0x400" vid="34" parent="-1" rk="0"/>
  <Value flg="0x400" vid="35" parent="-1" rk="0"/>
  <Value flg="0x400" vid="36" parent="-1" rk="1" sh-0="5"/>
  <Value flg="0x400" vid="37" parent="-1" rk="0"/>
  <Value flg="0x400" vid="38" parent="-1" rk="0"/>
  <Value flg="0x400" vid="39" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="40" parent="-1" rk="0"/>
  <Value flg="0x400" vid="41" parent="-1" rk="2" sh-0="68" sh-1="12"/>
  <Value flg="0x400" vid="42" parent="-1" rk="0"/>
  <Value flg="0x400" vid="43" parent="-1" rk="0"/>
  <Value flg="0x400" vid="44" parent="-1" rk="0"/>
  <Value flg="0x400" vid="45" parent="-1" rk="0"/>
  <Value flg="0x400" vid="46" parent="-1" rk="0"/>
  <Value flg="0x400" vid="47" parent="-1" rk="0"/>
  <Value flg="0x400" vid="48" parent="-1" rk="0"/>
  <Value flg="0x400" vid="49" parent="-1" rk="0"/>
  <Value flg="0x400" vid="50" parent="-1" rk="0"/>
  <Value flg="0x400" vid="51" parent="-1" rk="0"/>
  <Value flg="0x400" vid="52" parent="-1" rk="0"/>
  <Value flg="0x400" vid="53" parent="-1" rk="0"/>
  <Value flg="0x400" vid="54" parent="-1" rk="0"/>
  <Value flg="0x400" vid="55" parent="-1" rk="0"/>
  <Value flg="0x400" vid="56" parent="-1" rk="1" sh-0="39"/>
  <Value flg="0x400" vid="57" parent="-1" rk="0"/>
  <Value flg="0x400" vid="58" parent="-1" rk="0"/>
  <Value flg="0x400" vid="59" parent="-1" rk="0"/>
  <Value flg="0x400" vid="60" parent="-1" rk="0"/>
  <Value flg="0x400" vid="61" parent="-1" rk="0"/>
  <Value flg="0x400" vid="62" parent="-1" rk="0"/>
  <Value flg="0x400" vid="63" parent="-1" rk="0"/>
  <Value flg="0x400" vid="64" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="65" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="66" parent="-1" rk="1" sh-0="71"/>
  <Value flg="0x400" vid="67" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="68" parent="-1" rk="1" sh-0="57"/>
  <Value flg="0x400" vid="69" parent="-1" rk="0"/>
  <Value flg="0x400" vid="70" parent="-1" rk="0"/>
  <Value flg="0x400" vid="71" parent="-1" rk="1" sh-0="62"/>
  <Value flg="0x400" vid="72" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="73" parent="-1" rk="1" sh-0="87"/>
  <Value flg="0x400" vid="74" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="75" parent="-1" rk="1" sh-0="66"/>
  <Value flg="0x400" vid="76" parent="-1" rk="0"/>
  <Value flg="0x400" vid="77" parent="-1" rk="1" sh-0="15"/>
  <Value flg="0x400" vid="78" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="79" parent="-1" rk="0"/>
  <Value flg="0x400" vid="80" parent="-1" rk="0"/>
  <Value flg="0x400" vid="81" parent="-1" rk="0"/>
  <Value flg="0x400" vid="82" parent="-1" rk="0"/>
  <Value flg="0x400" vid="83" parent="-1" rk="1" sh-0="62"/>
  <Value flg="0x400" vid="84" parent="-1" rk="1" sh-0="63"/>
  <Value flg="0x400" vid="85" parent="-1" rk="0"/>
  <Value flg="0x400" vid="86" parent="-1" rk="1" sh-0="11"/>
  <Value flg="0x400" vid="87" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="88" parent="-1" rk="1" sh-0="5"/>
  <Value flg="0x400" vid="89" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="90" parent="-1" rk="1" sh-0="15"/>
  <Value flg="0x400" vid="91" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="92" parent="-1" rk="0"/>
  <Value flg="0x400" vid="93" parent="-1" rk="0"/>
  <Value flg="0x400" vid="94" parent="-1" rk="0"/>
  <Value flg="0x400" vid="95" parent="-1" rk="0"/>
  <Value flg="0x400" vid="96" parent="-1" rk="0"/>
  <Value flg="0x400" vid="97" parent="-1" rk="0"/>
  <Value flg="0x400" vid="98" parent="-1" rk="0"/>
  <Value flg="0x400" vid="99" parent="-1" rk="1" sh-0="41"/>
  <Value flg="0x400" vid="100" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="101" parent="-1" rk="1" sh-0="39"/>
  <Value flg="0x400" vid="102" parent="-1" rk="1" sh-0="52"/>
  <Value flg="0x400" vid="103" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="104" parent="-1" rk="1" sh-0="38"/>
  <Value flg="0x400" vid="105" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="106" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="107" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="108" parent="-1" rk="1" sh-0="5"/>
  <Value flg="0x400" vid="109" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="110" parent="-1" rk="1" sh-0="31"/>
  <Value flg="0x400" vid="111" parent="-1" rk="0"/>
  <Value flg="0x400" vid="112" parent="-1" rk="0"/>
  <Value flg="0x400" vid="113" parent="-1" rk="0"/>
  <Value flg="0x400" vid="114" parent="-1" rk="1" sh-0="15"/>
  <Value flg="0x400" vid="115" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="116" parent="-1" rk="0"/>
  <Value flg="0x400" vid="117" parent="-1" rk="0"/>
  <Value flg="0x400" vid="118" parent="-1" rk="0"/>
  <Value flg="0x400" vid="119" parent="-1" rk="0"/>
  <Value flg="0x400" vid="120" parent="-1" rk="1" sh-0="23"/>
  <Value flg="0x400" vid="121" parent="-1" rk="1" sh-0="35"/>
  <Value flg="0x400" vid="122" parent="-1" rk="0"/>
  <Value flg="0x400" vid="123" parent="-1" rk="1" sh-0="23"/>
  <Value flg="0x400" vid="124" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="125" parent="-1" rk="0"/>
  <Value flg="0x400" vid="126" parent="-1" rk="0"/>
  <Value flg="0x400" vid="127" parent="-1" rk="0"/>
  <Value flg="0x400" vid="128" parent="-1" rk="0"/>
  <Value flg="0x400" vid="129" parent="-1" rk="0"/>
  <Value flg="0x400" vid="130" parent="-1" rk="0"/>
  <Value flg="0x400" vid="131" parent="-1" rk="0"/>
  <Value flg="0x400" vid="132" parent="-1" rk="1" sh-0="41"/>
  <Value flg="0x400" vid="133" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="134" parent="-1" rk="1" sh-0="39"/>
  <Value flg="0x400" vid="135" parent="-1" rk="1" sh-0="52"/>
  <Value flg="0x400" vid="136" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="137" parent="-1" rk="1" sh-0="38"/>
  <Value flg="0x400" vid="138" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="139" parent="-1" rk="1" sh-0="2"/>
  <Value flg="0x400" vid="140" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="141" parent="-1" rk="1" sh-0="5"/>
  <Value flg="0x400" vid="142" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="143" parent="-1" rk="0"/>
  <Value flg="0x400" vid="144" parent="-1" rk="1" sh-0="31"/>
  <Value flg="0x400" vid="145" parent="-1" rk="0"/>
  <Value flg="0x400" vid="146" parent="-1" rk="0"/>
  <Value flg="0x400" vid="147" parent="-1" rk="0"/>
  <Value flg="0x400" vid="148" parent="-1" rk="1" sh-0="15"/>
  <Value flg="0x400" vid="149" parent="-1" rk="1" sh-0="0"/>
  <Value flg="0x400" vid="150" parent="-1" rk="0"/>
  <Value flg="0x400" vid="151" parent="-1" rk="0"/>
  <Value flg="0x400" vid="152" parent="-1" rk="0"/>
  <Value flg="0x400" vid="153" parent="-1" rk="0"/>
  <Value flg="0x400" vid="154" parent="-1" rk="1" sh-0="23"/>
  <Value flg="0x400" vid="155" parent="-1" rk="1" sh-0="35"/>
  <Value flg="0x400" vid="156" parent="-1" rk="0"/>
  <Ravel vid="0" cells="²SystemVariable.cc:740⁰"/>
  <Ravel vid="1" cells="³-1³0³0³0³0"/>
  <Ravel vid="2" cells="¹0¹1¹2¹3¹4¹5¹6¹7¹8¹9¹A
    ¹B¹C¹D¹E¹F¹10¹11¹12¹13¹14¹15¹16¹17¹18¹19¹1A¹1B¹1C¹1D¹1E¹1F² !⁰¹22²#$⁰
    ²%⁰¹26²'()*+,-./0123456789:;⁰¹3C²=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_⁰
    ²`abcdefghijklmnopqrstuvwxyz{|}~¥€⇄∧∼≬⋆⋸⌸⌺⌼μ⍁¡⍣⍅⎕⍞⌹⍆⍤⍇⍈⍊⊤λ⍍⍏£⊥⍶⌶⍐⍑χ⁰
    ²≢⍖⍗⍘⍚⍛⌈⍜⍢∪⍨⍕⍎⍬⍪∣│┤⍟∆∇→╣║╗╝←⌊┐└┴┬├─┼↑↓╔╚╩╦╠═╬≡⍸⍷∵⌷⍂⌻⊢⊣◊┘┌█▄▌▐▀⍺⍹⊂⊃⍝⍲⁰
    ²⍴⍱⌽⊖○∨⍳⍉∈∩⌿⍀≥≤≠×÷⍙∘⍵⍫⍋⍒¯¨ ⁰"/>
  <Ravel vid="3" cells="³0"/>
  <Ravel vid="4" cells="³-4"/>
  <Ravel vid="5" cells="³0"/>
  <Ravel vid="6" cells="³0"/>
  <Ravel vid="7" cells="³0"/>
  <Ravel vid="8" cells="³0³0"/>
  <Ravel vid="9" cells="³1"/>
  <Ravel vid="10" cells="³80"/>
  <Ravel vid="11" cells="³10"/>
  <Ravel vid="12" cells="³0"/>
  <Ravel vid="13" cells="³0"/>
  <Ravel vid="14" cells="² ⁰"/>
  <Ravel vid="15" cells="¹8¹D¹A
    "/>
  <Ravel vid="16" cells="³0"/>
  <Ravel vid="17" cells="³1"/>
  <Ravel vid="18" cells="³1"/>
  <Ravel vid="19" cells="².,⋆0_¯⁰"/>
  <Ravel vid="20" cells="³0"/>
  <Ravel vid="21" cells="² ⁰"/>
  <Ravel vid="22" cells="² ⁰"/>
  <Ravel vid="23" cells="³0"/>
  <Ravel vid="24" cells="³0"/>
  <Ravel vid="25" cells="³2"/>
  <Ravel vid="26" cells="³1"/>
  <Ravel vid="27" cells="³-1"/>
  <Ravel vid="28" cells="³1"/>
  <Ravel vid="29" cells="³1"/>
  <Ravel vid="30" cells="² ⁰"/>
  <Ravel vid="31" cells="² ⁰"/>
  <Ravel vid="32" cells="³1"/>
  <Ravel vid="33" cells="³1"/>
  <Ravel vid="34" cells="³0"/>
  <Ravel vid="35" cells="³0"/>
  <Ravel vid="36" cells="³2³3³4³5³6"/>
  <Ravel vid="37" cells="³0"/>
  <Ravel vid="38" cells="³3"/>
  <Ravel vid="39" cells="²__⁰"/>
  <Ravel vid="40" cells="³0"/>
  <Ravel vid="41" cells="²___         i           p           plot      ⁰
    ²  plotcomplex plotcomplexeplotfile    plotsincos  plotsincose ⎕AF  ⁰
    ²       ⎕AI         ⎕ARG        ⎕AT         ⎕AV         ⎕CR         ⁰
    ²⎕CT         ⎕DL         ⎕DLX        ⎕EA         ⎕EB         ⎕EC    ⁰
    ²     ⎕EM         ⎕ENV        ⎕ES         ⎕ET         ⎕EX         ⎕F⁰
    ²C         ⎕FFT        ⎕FIO        ⎕FX         ⎕GTK        ⎕INP     ⁰
    ²   ⎕IO         ⎕L          ⎕LC         ⎕LX         ⎕MAP        ⎕NA ⁰
    ²        ⎕NC         ⎕NL         ⎕PLOT       ⎕PP         ⎕PR        ⁰
    ² ⎕PS         ⎕PW         ⎕R          ⎕RE         ⎕RL         ⎕RVAL ⁰
    ²      ⎕SI         ⎕SQL        ⎕STOP       ⎕SVC        ⎕SVE        ⎕⁰
    ²SVO        ⎕SVQ        ⎕SVR        ⎕SVS        ⎕SYL        ⎕TC     ⁰
    ²    ⎕TF         ⎕TRACE      ⎕TS         ⎕TZ         ⎕UCS        ⎕UL⁰
    ²         ⎕WA         ⎕X          ⁰"/>
  <Ravel vid="42" cells="³2"/>
  <Ravel vid="43" cells="³128"/>
  <Ravel vid="44" cells="³6"/>
  <Ravel vid="45" cells="³1"/>
  <Ravel vid="46" cells="³128"/>
  <Ravel vid="47" cells="³6"/>
  <Ravel vid="48" cells="⁵                0J                1"/>
  <Ravel vid="49" cells="³2"/>
  <Ravel vid="50" cells="³128"/>
  <Ravel vid="51" cells="³6"/>
  <Ravel vid="52" cells="³1"/>
  <Ravel vid="53" cells="³128"/>
  <Ravel vid="54" cells="³6"/>
  <Ravel vid="55" cells="⁵                0J                1"/>
  <Ravel vid="56" cells="²background 255 0 0; dims 320 240; embed⁰"/>
  <Ravel vid="57" cells="³2"/>
  <Ravel vid="58" cells="³128"/>
  <Ravel vid="59" cells="³6"/>
  <Ravel vid="60" cells="³1"/>
  <Ravel vid="61" cells="³2"/>
  <Ravel vid="62" cells="³128"/>
  <Ravel vid="63" cells="³6"/>
  <Ravel vid="64" cells="²xy⁰"/>
  <Ravel vid="65" cells="² ⁰"/>
  <Ravel vid="66" cells="²bgwhite; xcol 1; tlabel ⁰¹22²Lissajous axis 1⁰
    ¹22²; dest png; file ⁰¹22²lissa1.png⁰¹22"/>
  <Ravel vid="67" cells="³2³128"/>
  <Ravel vid="68" cells="²both; ylog on; tlabel ⁰¹22²y = 2^x⁰¹22²; dest ⁰
    ²eps; file ⁰¹22²log.eps⁰¹22"/>
  <Ravel vid="69" cells="³2"/>
  <Ravel vid="70" cells="³100"/>
  <Ravel vid="71" cells="²xcol 0; tlabel ⁰¹22²Lissajous axis 0⁰¹22²; des⁰
    ²t pdf; file ⁰¹22²lissa0.pdf⁰¹22"/>
  <Ravel vid="72" cells="³2³128"/>
  <Ravel vid="73" cells="²both; background 100 100 255;xcol -1; tlabel ⁰
    ¹22²sin and cos⁰¹22²; dest svg; file ⁰¹22²sincos.svg⁰¹22"/>
  <Ravel vid="74" cells="³2³128"/>
  <Ravel vid="75" cells="²lines; tlabel ⁰¹22²Product of sin and cos⁰¹22²;⁰
    ² dest ps; file ⁰¹22²product.ps⁰¹22"/>
  <Ravel vid="76" cells="³10"/>
  <Ravel vid="77" cells="²lines; ylog off⁰"/>
  <Ravel vid="78" cells="² ⁰"/>
  <Ravel vid="79" cells="³1"/>
  <Ravel vid="80" cells="³128"/>
  <Ravel vid="81" cells="³6"/>
  <Ravel vid="82" cells="⁵                0J                1"/>
  <Ravel vid="83" cells="²bgblack; tlabel ⁰¹22²Complex vector⁰¹22²; dest⁰
    ² png; file ⁰¹22²complex.png⁰¹22"/>
  <Ravel vid="84" cells="²tlabel ⁰¹22²Polar plot⁰¹22²; polar; degrees; d⁰
    ²est png; file ⁰¹22²polar.png⁰¹22"/>
  <Ravel vid="85" cells="³360"/>
  <Ravel vid="86" cells="²dest screen⁰"/>
  <Ravel vid="87" cells="² ⁰"/>
  <Ravel vid="88" cells="²reset⁰"/>
  <Ravel vid="89" cells="² ⁰"/>
  <Ravel vid="90" cells="²dest screen; xy⁰"/>
  <Ravel vid="91" cells="² ⁰"/>
  <Ravel vid="92" cells="³2"/>
  <Ravel vid="93" cells="³128"/>
  <Ravel vid="94" cells="³6"/>
  <Ravel vid="95" cells="³1"/>
  <Ravel vid="96" cells="³2"/>
  <Ravel vid="97" cells="³128"/>
  <Ravel vid="98" cells="³6"/>
  <Ravel vid="99" cells="²bgwhite;xcol 1; tlabel ⁰¹22²Lissajous axis 1⁰
    ¹22"/>
  <Ravel vid="100" cells="³2³128"/>
  <Ravel vid="101" cells="²points; tlabel ⁰¹22²Product of sin and cos⁰
    ¹22"/>
  <Ravel vid="102" cells="²background 0 0 255;xcol 0; tlabel ⁰¹22²Lissaj⁰
    ²ous axis 0⁰¹22"/>
  <Ravel vid="103" cells="³2³128"/>
  <Ravel vid="104" cells="²bgblack; xcol -1; tlabel ⁰¹22²sin and cos⁰¹22"/>
  <Ravel vid="105" cells="³2³128"/>
  <Ravel vid="106" cells="²xy⁰"/>
  <Ravel vid="107" cells="² ⁰"/>
  <Ravel vid="108" cells="²reset⁰"/>
  <Ravel vid="109" cells="² ⁰"/>
  <Ravel vid="110" cells="²both; ylog on; tlabel ⁰¹22²y = 2^x⁰¹22"/>
  <Ravel vid="111" cells="³2"/>
  <Ravel vid="112" cells="³100"/>
  <Ravel vid="113" cells="³10"/>
  <Ravel vid="114" cells="²lines; ylog off⁰"/>
  <Ravel vid="115" cells="² ⁰"/>
  <Ravel vid="116" cells="³1"/>
  <Ravel vid="117" cells="³128"/>
  <Ravel vid="118" cells="³6"/>
  <Ravel vid="119" cells="⁵                0J                1"/>
  <Ravel vid="120" cells="²tlabel ⁰¹22²Complex vector⁰¹22"/>
  <Ravel vid="121" cells="²tlabel ⁰¹22²Polar plot⁰¹22²; polar; degrees⁰"/>
  <Ravel vid="122" cells="³360"/>
  <Ravel vid="123" cells="²dims 320 240; embed; xy⁰"/>
  <Ravel vid="124" cells="² ⁰"/>
  <Ravel vid="125" cells="³2"/>
  <Ravel vid="126" cells="³128"/>
  <Ravel vid="127" cells="³6"/>
  <Ravel vid="128" cells="³1"/>
  <Ravel vid="129" cells="³2"/>
  <Ravel vid="130" cells="³128"/>
  <Ravel vid="131" cells="³6"/>
  <Ravel vid="132" cells="²bgwhite;xcol 1; tlabel ⁰¹22²Lissajous axis 1⁰
    ¹22"/>
  <Ravel vid="133" cells="³2³128"/>
  <Ravel vid="134" cells="²points; tlabel ⁰¹22²Product of sin and cos⁰
    ¹22"/>
  <Ravel vid="135" cells="²background 0 0 255;xcol 0; tlabel ⁰¹22²Lissaj⁰
    ²ous axis 0⁰¹22"/>
  <Ravel vid="136" cells="³2³128"/>
  <Ravel vid="137" cells="²bgblack; xcol -1; tlabel ⁰¹22²sin and cos⁰¹22"/>
  <Ravel vid="138" cells="³2³128"/>
  <Ravel vid="139" cells="²xy⁰"/>
  <Ravel vid="140" cells="² ⁰"/>
  <Ravel vid="141" cells="²reset⁰"/>
  <Ravel vid="142" cells="² ⁰"/>
  <Ravel vid="143" cells="⁴1e-13"/>
  <Ravel vid="144" cells="²both; ylog on; tlabel ⁰¹22²y = 2^x⁰¹22"/>
  <Ravel vid="145" cells="³2"/>
  <Ravel vid="146" cells="³100"/>
  <Ravel vid="147" cells="³10"/>
  <Ravel vid="148" cells="²lines; ylog off⁰"/>
  <Ravel vid="149" cells="² ⁰"/>
  <Ravel vid="150" cells="³1"/>
  <Ravel vid="151" cells="³128"/>
  <Ravel vid="152" cells="³6"/>
  <Ravel vid="153" cells="⁵                0J                1"/>
  <Ravel vid="154" cells="²tlabel ⁰¹22²Complex vector⁰¹22"/>
  <Ravel vid="155" cells="²tlabel ⁰¹22²Polar plot⁰¹22²; polar; degrees⁰"/>
  <Ravel vid="156" cells="³360"/>
  <SymbolTable size="8">
    <Symbol name="_" stack-size="1">
      <Variable vid="41"/>
    </Symbol>

    <Symbol name="___" stack-size="1">
      <Function creation-time="1593480348120461" exec-properties="0,0,0,0">
        <UCS uni="²z←i ___ p;m⁰¹A
                  ²⍝ aplwrap tab-completion helper⁰¹A
                  ²→(0≤i)/F⁰¹A
                  ²→(3≠⎕nc '__')/D⁰¹A
                  ²_←__ p⁰¹A
                  ²→0⁰¹A
                  ²D: _←⎕nl 2 3 4 5 6⁰¹A
                  ²→0⁰¹A
                  ²F: →(0=⍴_)/E⁰¹A
                  ²m←((,1↑[⎕io+1]p⍷_)⌿_)⍪' '⁰¹A
                  ²z←((' '≠z)/z←m[((⎕io-1)+↑⍴m)⌊⎕io⌈⎕io+i;])⁰¹A
                  ²z←((⎕io+1+×i-¯1+↑⍴m)⌷(i+1),2⍴0) z⁰¹A
                  ²→0⁰¹A
                  ²E: z←''⁰¹A
                  "/>
      </Function>
    </Symbol>

    <Symbol name="plot" stack-size="1">
      <Function creation-time="-1" exec-properties="1,1,1,0" native="1">
        <UCS uni="²libaplplot.so⁰"/>
      </Function>
    </Symbol>

    <Symbol name="plotcomplex" stack-size="1">
      <Function creation-time="1410217867638630" exec-properties="0,0,0,0">
        <UCS uni="²plotcomplex;c;s;z⁰¹A
                  ²c←2○(⍳128)÷6⁰¹A
                  ²s←1○(⍳128)÷6⁰¹A
                  ²z←c+s×0J1⁰¹A
                  ²plot z⁰¹A
                  "/>
      </Function>
    </Symbol>

    <Symbol name="plotcomplexe" stack-size="1">
      <Function creation-time="1410828280066515" exec-properties="0,0,0,0">
        <UCS uni="²plotcomplexe;c;s;z⁰¹A
                  ²c←2○(⍳128)÷6⁰¹A
                  ²s←1○(⍳128)÷6⁰¹A
                  ²z←c+s×0J1⁰¹A
                  ²'background 255 0 0; dims 320 240; embed' plot z⁰¹A
                  "/>
      </Function>
    </Symbol>

    <Symbol name="plotfile" stack-size="1">
      <Function creation-time="-1" exec-properties="0,0,0,0">
        <UCS uni="²plotfile;c;s;p;q⁰¹A
                  ²c←2○(⍳128)÷6⁰¹A
                  ²s←1○2×(⍳128)÷6⁰¹A
                  ²'xy' plot ''⁰¹A
                  ²'bgwhite; xcol 1; tlabel ⁰¹22²Lissajous axis 1⁰¹22²; ⁰
                  ²dest png; file ⁰¹22²lissa1.png⁰¹22²' plot ⍉2 128⍴s,c⁰¹A
                  ²'xcol 0; tlabel ⁰¹22²Lissajous axis 0⁰¹22²; dest pdf;⁰
                  ² file ⁰¹22²lissa0.pdf⁰¹22²' plot ⍉2 128⍴s,c⁰¹A
                  ²'both; background 100 100 255;xcol -1; tlabel ⁰¹22²si⁰
                  ²n and cos⁰¹22²; dest svg; file ⁰¹22²sincos.svg⁰¹22²' ⁰
                  ²plot ⍉2 128⍴s,c⁰¹A
                  ²p ←s×c⁰¹A
                  ²'lines; tlabel ⁰¹22²Product of sin and cos⁰¹22²; dest⁰
                  ² ps; file ⁰¹22²product.ps⁰¹22²' plot p⁰¹A
                  ²'both; ylog on; tlabel ⁰¹22²y = 2^x⁰¹22²; dest eps; f⁰
                  ²ile ⁰¹22²log.eps⁰¹22²' plot 2⋆((⍳100)÷10)⁰¹A
                  ²'lines; ylog off' plot ''⁰¹A
                  ²s←1○(⍳128)÷6⁰¹A
                  ²q←c+s×0J1⁰¹A
                  ²'bgblack; tlabel ⁰¹22²Complex vector⁰¹22²; dest png; ⁰
                  ²file ⁰¹22²complex.png⁰¹22²' plot q⁰¹A
                  ²'tlabel ⁰¹22²Polar plot⁰¹22²; polar; degrees; dest pn⁰
                  ²g; file ⁰¹22²polar.png⁰¹22²' plot ⍳360⁰¹A
                  ²'dest screen' plot ''⁰¹A
                  ²'reset' plot ''⁰¹A
                  "/>
      </Function>
    </Symbol>

    <Symbol name="plotsincos" stack-size="1">
      <Function creation-time="-1" exec-properties="0,0,0,0">
        <UCS uni="²z←plotsincos;c;s;p;q;a⁰¹A
                  ²'dest screen; xy' plot ''⁰¹A
                  ²c←2○(⍳128)÷6⁰¹A
                  ²s←1○2×(⍳128)÷6⁰¹A
                  ²a←'bgwhite;xcol 1; tlabel ⁰¹22²Lissajous axis 1⁰¹22²'⁰
                  ² plot ⍉2 128⍴s,c⁰¹A
                  ²a←a,'background 0 0 255;xcol 0; tlabel ⁰¹22²Lissajous⁰
                  ² axis 0⁰¹22²' plot ⍉2 128⍴s,c⁰¹A
                  ²a←a,'bgblack; xcol -1; tlabel ⁰¹22²sin and cos⁰¹22²' ⁰
                  ²plot ⍉2 128⍴s,c⁰¹A
                  ²p ←s×c⁰¹A
                  ²a←a,'points; tlabel ⁰¹22²Product of sin and cos⁰¹22²'⁰
                  ² plot p⁰¹A
                  ²a←a,'both; ylog on; tlabel ⁰¹22²y = 2^x⁰¹22²' plot 2⋆⁰
                  ²((⍳100)÷10)⁰¹A
                  ²'lines; ylog off' plot ''⁰¹A
                  ²s←1○(⍳128)÷6⁰¹A
                  ²q←c+s×0J1⁰¹A
                  ²a←a,'tlabel ⁰¹22²Complex vector⁰¹22²' plot q⁰¹A
                  ²a←a,'tlabel ⁰¹22²Polar plot⁰¹22²; polar; degrees' plo⁰
                  ²t ⍳360⁰¹A
                  ²'xy' plot ''⁰¹A
                  ²z←a⁰¹A
                  ²'reset' plot ''⁰¹A
                  "/>
      </Function>
    </Symbol>

    <Symbol name="plotsincose" stack-size="1">
      <Function creation-time="1410477436775625" exec-properties="0,0,0,0">
        <UCS uni="²z←plotsincose;c;s;p;q;a⁰¹A
                  ²'dims 320 240; embed; xy' plot ''⁰¹A
                  ²c←2○(⍳128)÷6⁰¹A
                  ²s←1○2×(⍳128)÷6⁰¹A
                  ²a←'bgwhite;xcol 1; tlabel ⁰¹22²Lissajous axis 1⁰¹22²'⁰
                  ² plot ⍉2 128⍴s,c⁰¹A
                  ²a←a,'background 0 0 255;xcol 0; tlabel ⁰¹22²Lissajous⁰
                  ² axis 0⁰¹22²' plot ⍉2 128⍴s,c⁰¹A
                  ²a←a,'bgblack; xcol -1; tlabel ⁰¹22²sin and cos⁰¹22²' ⁰
                  ²plot ⍉2 128⍴s,c⁰¹A
                  ²p ←s×c⁰¹A
                  ²a←a,'points; tlabel ⁰¹22²Product of sin and cos⁰¹22²'⁰
                  ² plot p⁰¹A
                  ²a←a,'both; ylog on; tlabel ⁰¹22²y = 2^x⁰¹22²' plot 2⋆⁰
                  ²((⍳100)÷10)⁰¹A
                  ²'lines; ylog off' plot ''⁰¹A
                  ²s←1○(⍳128)÷6⁰¹A
                  ²q←c+s×0J1⁰¹A
                  ²a←a,'tlabel ⁰¹22²Complex vector⁰¹22²' plot q⁰¹A
                  ²a←a,'tlabel ⁰¹22²Polar plot⁰¹22²; polar; degrees' plo⁰
                  ²t ⍳360⁰¹A
                  ²'xy' plot ''⁰¹A
                  ²z←a⁰¹A
                  ²'reset' plot ''⁰¹A
                  "/>
      </Function>
    </Symbol>

  </SymbolTable>

  <Symbol name="⎕AI" stack-size="1">
    <Variable vid="1"/>
  </Symbol>

  <Symbol name="⎕ARG" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⎕AV" stack-size="1">
    <Variable vid="2"/>
  </Symbol>

  <Symbol name="⎕CT" stack-size="1">
    <Variable vid="143"/>
  </Symbol>

  <Symbol name="⎕EM" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⎕ET" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⎕FC" stack-size="1">
    <Variable vid="19"/>
  </Symbol>

  <Symbol name="⎕IO" stack-size="1">
    <Variable vid="17"/>
  </Symbol>

  <Symbol name="⎕L" stack-size="1">
    <Variable vid="12"/>
  </Symbol>

  <Symbol name="⎕LC" stack-size="1">
    <Variable vid="6"/>
  </Symbol>

  <Symbol name="⎕LX" stack-size="1">
    <Variable vid="14"/>
  </Symbol>

  <Symbol name="⎕PP" stack-size="1">
    <Variable vid="11"/>
  </Symbol>

  <Symbol name="⎕PR" stack-size="1">
    <Variable vid="21"/>
  </Symbol>

  <Symbol name="⎕PS" stack-size="1">
    <Variable vid="8"/>
  </Symbol>

  <Symbol name="⎕PW" stack-size="1">
    <Variable vid="10"/>
  </Symbol>

  <Symbol name="⎕R" stack-size="1">
    <Variable vid="7"/>
  </Symbol>

  <Symbol name="⎕RL" stack-size="1">
    <Variable vid="9"/>
  </Symbol>

  <Symbol name="⎕SVE" stack-size="1">
    <Variable vid="13"/>
  </Symbol>

  <Symbol name="⎕SYL" stack-size="1">
    <Variable vid="5"/>
  </Symbol>

  <Symbol name="⎕TC" stack-size="1">
    <Variable vid="15"/>
  </Symbol>

  <Symbol name="⎕TS" stack-size="1">
    <Variable vid="16"/>
  </Symbol>

  <Symbol name="⎕TZ" stack-size="1">
    <Variable vid="4"/>
  </Symbol>

  <Symbol name="⎕UL" stack-size="1">
    <Variable vid="18"/>
  </Symbol>

  <Symbol name="⎕X" stack-size="1">
    <Variable vid="3"/>
  </Symbol>

  <Symbol name="⎕WA" stack-size="1">
    <Variable vid="20"/>
  </Symbol>

  <Symbol name="λ" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⍺" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⍵" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="χ" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⍶" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⍹" stack-size="1">
    <unused-name/>
  </Symbol>

  <StateIndicator levels="0">
  </StateIndicator>

</Workspace>
    
